
title: Saddam Howlader | IT Professional
email: asifnowlader4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  IT Officer and Cybersecurity specialist focused on Digital Forensics and IT Excellence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: saddamhowlader6
github_username: saddamhowlader
linkedin_username: saddamhowlader

# Build settings
theme: minima
plugins:
  - jekyll-feed
